INGK-519 Test python ethernet implementation
ingeniamc/ingenialink-python pull request #218
Opened 2022-10-13 08:37 UTC by MartinALL91

2022-10-13 13:45 UTC, WoodElv approved these changes

2022-10-18 15:31 UTC, GullinBustin requested changes

2022-10-18 15:31 UTC, GullinBustin commented on ingenialink/utils/_utils.py
> +        REG_DTYPE.S32: 4
What happens if dtype is U32

2022-10-18 15:31 UTC, GullinBustin commented on ingenialink/ethernet/servo.py
> +        """SERVO_UNITS_ACC: Acceleration units."""
What are these variables for?

2022-10-19 16:13 UTC, GullinBustin commented on ingenialink/ethernet/servo.py
> +        """SERVO_UNITS_ACC: Acceleration units."""
:( I will create an issue to solve it

2022-10-19 16:13 UTC, GullinBustin approved these changes

2022-10-19 16:13 UTC, merged