INGK-524 Set timeout on socket
ingeniamc/ingenialink-python pull request #219
Opened 2022-10-14 12:54 UTC by MartinALL91

2022-10-14 13:02 UTC, GullinBustin requested changes

2022-10-14 13:02 UTC, GullinBustin commented on ingenialink/ethernet/servo.py
> +                raise ILIOError from e
I think this error message should be inside the exception:
raise ILIOError("Error receiving data") from e

Same with the others excepts

2022-10-14 13:10 UTC, GullinBustin approved these changes

2022-10-18 15:36 UTC, WoodElv approved these changes

2022-10-19 16:10 UTC, merged