INGK-526 delete ffi and lib dependencies for servos modules
ingeniamc/ingenialink-python pull request #226
Opened 2022-10-20 10:19 UTC by WoodElv

2022-10-20 14:24 UTC, MartinALL91 commented on ingenialink/servo.py
> +        il_etimedout = -3
I think this value should the defined some place else

2022-10-24 09:19 UTC, GullinBustin requested changes

2022-10-28 08:10 UTC, GullinBustin approved these changes

2022-11-15 10:37 UTC, MartinALL91 approved these changes

2022-11-22 16:40 UTC, merged