INGK-533 Interface network class soem service
ingeniamc/ingenialink-python pull request #229
Opened 2022-10-31 17:25 UTC by MartinALL91

2022-11-09 11:42 UTC, WoodElv approved these changes

2023-01-05 15:56 UTC, GullinBustin requested changes
Add unit test

2023-01-05 15:56 UTC, GullinBustin commented on ingenialink/eoe/network.py
> +        to the EoE service.
The docstring format is not right, try to use black

2023-01-05 16:06 UTC, GullinBustin commented
I just see the tests in https://github.com/ingeniamc/ingenialink-python/pull/234#pullrequestreview-1237652189

2023-01-13 10:35 UTC, MartinALL91 commented on ingenialink/eoe/network.py
> +        return super().connect_to_slave(target, dictionary,
To enable multi-drive communication.

2023-01-23 08:43 UTC, GullinBustin approved these changes

2023-01-31 13:51 UTC, merged