INGK-540 Add multi slave support
ingeniamc/ingenialink-python pull request #230
Opened 2022-11-04 10:12 UTC by MartinALL91

The EoE service must be started manually after the drives have been configured. This is because the feature to stop the service is not yet implemented.

2022-11-09 11:55 UTC, WoodElv approved these changes

2023-01-05 15:59 UTC, GullinBustin requested changes

2023-01-05 15:59 UTC, GullinBustin commented on ingenialink/eoe/network.py
> +    def start_eoe_service(self):
Maybe you can implement a message to ask if the service was started.

2023-01-23 11:20 UTC, GullinBustin approved these changes

2023-01-31 13:52 UTC, merged