INGK-570 Improve the tests of the servo module
ingeniamc/ingenialink-python pull request #247
Opened 2022-11-29 11:16 UTC by pzinemanas

## Improve the tests of the servo module

### Description

This PR improves the tests of functions shared by all protocols, mainly those from the servo module.

Fixes # INGK-570

### Type of change

- [x] Create a `servo._read_configuration_file` function to read a configuration file. This simplifies the tests of `load_configuration` and `save_configuration`.
- [x] Create a test for the new function.
- [x] Add an XCF reference file to test the `load_configuration` and `save_configuration` functions.
- [x] Improve the tests of `load_configuration` and `save_configuration`.
- [x] Improve the test_write function. 

### Tests
- [x] Run tests and obtain similar coverage.

2022-12-05 10:57 UTC, MartinALL91 requested changes

2022-12-05 10:57 UTC, MartinALL91 commented on ingenialink/servo.py
> +        Args:
Leave a blank line.

2022-12-05 10:57 UTC, MartinALL91 commented on ingenialink/servo.py
> +        Returns:
Blank line.

2022-12-05 10:57 UTC, MartinALL91 commented on ingenialink/servo.py
> +        Raises:
Blank line.

2022-12-05 10:57 UTC, MartinALL91 commented on ingenialink/servo.py
> +    def _read_configuration_file(self, config_file):
This function can be static.

2022-12-05 10:57 UTC, MartinALL91 commented on tests/test_servo.py
> -        assert access == "rw"
I think these assertions should not be removed.

2022-12-20 12:26 UTC, GullinBustin approved these changes

2022-12-22 10:50 UTC, WoodElv approved these changes

2023-01-02 09:17 UTC, MartinALL91 approved these changes

2023-01-02 09:19 UTC, merged