INGK-579 Avoid repeated code between the Servo children
ingeniamc/ingenialink-python pull request #251
Opened 2022-12-01 11:13 UTC by pzinemanas

##  Avoid repeated code between the Servo children

### Description

This PR moves some functions of the Servo children to the Servo parent. This simplifies the code and avoids possible bugs when re-defining abstract methods in the children. Only two methods are kept as abstract methods:  `read_raw` and `write_raw`. Those are protocol-dependent methods to write and read byte arrays.

Fixes # INGK-579

### Type of change

- [x] Add a `DICTIONARY_CLASS` constant at the `Servo` class, which stores the `Dictionary` class related to the `Servo` (e.g., `CanopenDictionary` for `CanopenServo`).
- [x]  Add a `MAX_WRITE_SIZE ` constant at the `Servo` class, which stores the disturbance max size for each protocol.
- [x] Creates `read_raw` and `write_raw` abstract methods at the `Servo` parent. 
- [x] Define `write` and `read` functions at the parent. These functions use `read_raw` and `write_raw` defined for each protocol.
- [x] Define `replace_dictionary` at the `Servo` parent.
- [x] Define `disturbance_write_data` at the `Servo` parent.
- [x] Define `_monitoring_read_data` at the `Servo` parent.

### Tests
- [x] Run tests and obtain similar coverage.

2022-12-05 12:58 UTC, MartinALL91 requested changes

2022-12-05 12:58 UTC, MartinALL91 commented on ingenialink/canopen/servo.py
>          value = None
This line is not necessary.

2022-12-05 12:58 UTC, MartinALL91 commented on ingenialink/servo.py
> +    def __init__(self, target, dictionary_path=None, servo_status_listener=False):
The docstring needs to be updated.

2022-12-05 12:58 UTC, MartinALL91 commented on ingenialink/servo.py
> +        """Writes a raw bytes data to a target register.
Write raw bytes to a target register.

2022-12-05 12:58 UTC, MartinALL91 commented on ingenialink/servo.py
> +        """Read raw bytes from servo.
Read raw bytes from a target register.

2022-12-20 14:24 UTC, GullinBustin approved these changes

2022-12-27 11:14 UTC, MartinALL91 approved these changes

2023-01-02 09:17 UTC, merged