INGK-584 Remove ingenialink c
ingeniamc/ingenialink-python pull request #257
Opened 2022-12-30 10:14 UTC by MartinALL91

### Description

This PR removes all references to the ingenialink C library.

Fixes # INGK-584

### Type of change

- Remove IPB module
- Strip EthercatNetwork class (in the near future it will only contain a function to load firmware files via FOE)
- Remove register_deprecated.py, dictionary_deprecated.py
- Remove some unused files (travis.yml, wpcap.lib, ect)
- Update documentation
- Update CHANGELOG
- Update setup.py (remove the step of building ingenialink C) 

### Tests
- Generated documentation without errors.
- Generated wheel without errors.
- Tested wheel by performing basic tasks (connection/disconnection, reading a register)

2023-01-02 09:28 UTC, WoodElv approved these changes

2023-01-02 15:55 UTC, pzinemanas approved these changes

2023-01-23 11:31 UTC, GullinBustin requested changes
It looks good, but resolve the conflicts

2023-01-23 15:38 UTC, MartinALL91 commented
> It looks good, but resolve the conflicts

Done

2023-02-01 10:08 UTC, GullinBustin approved these changes

2023-02-01 10:09 UTC, merged