INGK-592 Improve load_FW script using canopen
ingeniamc/ingenialink-python pull request #271
Opened 2023-01-16 14:49 UTC by pzinemanas

## Improve load_FW script using canopen

### Description

This script improves the load_FW script using canopen by adding attempts and catching errors.

Fixes # INGK-592

### Type of change

- [x] Add attempts.
- [x] Catch errors.

### Tests
- [x] Tested locally
- [x] Tested remotely with Jenkins.

### Documentation

- [x] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2023-01-17 17:33 UTC, MartinALL91 approved these changes

2023-01-17 17:33 UTC, MartinALL91 commented on tests/resources/Scripts/load_FWs.py
> +            logger.info("New FW detected after: {:.1f} s".format(time.perf_counter() - ini_time))
Use an f-string

2023-01-17 17:33 UTC, MartinALL91 commented on tests/resources/Scripts/load_FWs.py
> +            logger.info("New FW detected after: {:.1f} s".format(time.perf_counter() - ini_time))
It could be useful to also log the firmware version stored in the drive.

2023-01-17 17:33 UTC, MartinALL91 commented on tests/resources/Scripts/load_FWs.py
> +        raise Exception("New FW not detected")
This message can be misleading. What is actually happening is that we're unable to connect to the drive.

2023-01-23 13:32 UTC, WoodElv approved these changes

2023-01-23 13:32 UTC, WoodElv commented on tests/resources/Scripts/load_FWs.py
> +        except Exception as e:
Is there an specific exception for a no connection?

2023-02-03 13:44 UTC, GullinBustin requested changes
Apply comments changes

2023-02-06 09:49 UTC, GullinBustin approved these changes

2023-02-06 10:34 UTC, merged