INGK-641 Fix the path of the FoE application
ingeniamc/ingenialink-python pull request #298
Opened 2023-04-27 11:01 UTC by pzinemanas

Fix the path of the FoE application

### Description

This PR changes the way to find the path to the FoE application. It uses inspect module instead of pkg_resources. This is needed to use FoE from ML3.

Fixes # INGK-641

### Type of change

- [x] Use inspect instead of pkg_resources.

### Tests
- [x] Run tests.

### Documentation

Please update the documentation.

- [x] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2023-04-27 13:13 UTC, GullinBustin requested changes
Remove 'importlib-resources==5.4.0' from setup.py and requirement files

2023-04-27 14:29 UTC, GullinBustin approved these changes

2023-04-27 14:53 UTC, WoodElv approved these changes

2023-04-28 10:42 UTC, MartinALL91 approved these changes

2023-05-02 15:44 UTC, merged