INGK-743 Load dictionary by default in the virtual drive
ingeniamc/ingenialink-python pull request #349
Opened 2024-01-04 14:14 UTC by pzinemanas

## Load dictionary by default in the virtual drive

### Description

This PR loads a default dictionary in the virtual drive.

Fixes # INGK-743

### Type of change

Please add a description and delete options that are not relevant.

- [x] Load dictionary by default in the virtual drive
- [x] Move default dictionary from tests to module folder.

### Tests
- [x] Add new unit tests if it applies.
- [x] Run tests.

### Documentation

Please update the documentation.

- [x] Update docstrings of every function, method or class that change.
- [x] Build documentation locally to verify changes.
- [x] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2024-01-05 11:38 UTC, WoodElv approved these changes

2024-01-09 10:33 UTC, GullinBustin requested changes

2024-01-09 10:33 UTC, GullinBustin commented on tests/test_dictionary.py
> +path_to_dictionary = "./ingenialink/virtual/resources/virtual_drive.xdf"
Use Uppercase to constants

2024-01-09 10:33 UTC, GullinBustin commented on ingenialink/virtual/virtual_drive.py
> +            pathlib.Path(__file__).parent.resolve(), "./resources/virtual_drive.xdf"
Use constants instead literal

2024-01-09 10:44 UTC, pzinemanas commented on ingenialink/virtual/virtual_drive.py
> +            pathlib.Path(__file__).parent.resolve(), "./resources/virtual_drive.xdf"
Done!

2024-01-09 10:44 UTC, pzinemanas commented on tests/test_dictionary.py
> +path_to_dictionary = "./ingenialink/virtual/resources/virtual_drive.xdf"
Done!

2024-01-09 11:58 UTC, merged