INGK-741 Initialize registers of virtual drive using an XCF file
ingeniamc/ingenialink-python pull request #350
Opened 2024-01-04 15:43 UTC by pzinemanas

## Initialize registers of the virtual drive using an XCF file

### Description

This PR adds an XCF file to initialize the registers of the virtual drive.

Fixes # INGK-741

### Type of change

- [x] Add XCF file.
- [x] Load default values from the XCF file.

### Tests
- [x] Add new unit tests if it applies.
- [x] Run tests.

### Documentation

Please update the documentation.

- [x] Update docstrings of every function, method or class that change.
- [x] Build documentation locally to verify changes.
- [x] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2024-01-05 11:42 UTC, WoodElv approved these changes

2024-01-09 10:33 UTC, GullinBustin requested changes

2024-01-09 10:33 UTC, GullinBustin commented on ingenialink/virtual/virtual_drive.py
> +            pathlib.Path(__file__).parent.resolve(), "./resources/virtual_drive.xcf"
Use constant instead literal

2024-01-09 10:48 UTC, pzinemanas commented on ingenialink/virtual/virtual_drive.py
> +            pathlib.Path(__file__).parent.resolve(), "./resources/virtual_drive.xcf"
Done!

2024-01-09 10:48 UTC, GullinBustin approved these changes

2024-01-09 10:55 UTC, merged