INGK-837 Don't reset PDO mapping when mapping PDOs
ingeniamc/ingenialink-python pull request #381
Opened 2024-03-04 11:52 UTC by MartinALL91

### Description

Don't reset PDO mapping when mapping PDOs

Fixes # INGK-837

### Type of change

- Remove calls to reset_rpdo_mapping and  reset_tpdo_mapping on the set_pdo_map_to_slave method.
- Extend the PDOMap lists with the PDOMaps when calling the set_pdo_map_to_slave method.
- Add the reset_pdo_mapping method.
- Add the remove_rpdo_map method.
- Add the remove_tpdo_map method.

### Tests
- [x] Add new unit tests if it applies.
- [x] Run tests.

### Documentation

Please update the documentation.

- [x] Update docstrings of every function, method or class that change.
- [x] Build documentation locally to verify changes.

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2024-03-04 16:21 UTC, pzinemanas approved these changes

2024-03-06 15:54 UTC, GullinBustin requested changes

2024-03-06 15:54 UTC, GullinBustin commented on tests/ethercat/test_pdo.py
> +        servo.reset_pdo_mapping()
I think reset should de done in the Servo PDO constructor or similar. To ensure the inital state.

2024-03-06 15:54 UTC, GullinBustin commented on tests/ethercat/test_pdo.py
> +        servo.reset_pdo_mapping()
In addition, you can add a test or expand this test to check that you can stop PDOs and start it again with the same configuration if you don't reset the mapping.

2024-03-08 08:32 UTC, WoodElv approved these changes

2024-03-11 17:11 UTC, merged