INGK-791 Add documentation about how to use the library on Linux
ingeniamc/ingenialink-python pull request #392
Opened 2024-03-27 14:35 UTC by pzinemanas

## Add documentation about how to use the library on Linux

### Description

Fixes INGK-791

### Type of change

Please add a description and delete options that are not relevant.

- [x] Add example
- [x] Add documentation

### Documentation

Please update the documentation.

- [x] Update docstrings of every function, method or class that change.
- [x] Build documentation locally to verify changes.
- [ ] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2024-03-28 11:42 UTC, MartinALL91 approved these changes

2024-04-04 09:12 UTC, WoodElv approved these changes

2024-04-04 09:17 UTC, GullinBustin requested changes

2024-04-04 09:17 UTC, GullinBustin commented on examples/canopen/can_connection_linux.py
> +    connection_example()
Can you add a dictionary path as an argument to allow testing it in the future?

2024-04-05 09:57 UTC, merged