INGK-861 Support cyclic TXRX in dictionary v 3
ingeniamc/ingenialink-python pull request #398
Opened 2024-04-11 11:15 UTC by MartinALL91

### Description

Support cyclic TXRX in dictionary v 3

Fixes # INGK-861

### Type of change

- Create an enum for the register cyclic attribute.
- Add cyclic TXRX as an accepted cyclic type in the PDOMapItem class.

### Tests
- [x] Run tests.

I added a new register with cyclic type TXRX to the EtherCAT V3 example dictionary, updated the necessary tests, and checked that all the tests passed.

### Code formatting

- [x] Use black package to format the code: `black -l 100 ingenialink tests`. It is recommended to configure the code editor to automatically format the code using black with a max length line of 100.

2024-04-12 10:20 UTC, GullinBustin requested changes

2024-04-12 10:20 UTC, GullinBustin commented on ingenialink/enums/register.py
> +class REG_CYCLIC_TYPE(Enum):
CamelCase

2024-04-15 08:48 UTC, pzinemanas approved these changes

2024-04-15 09:11 UTC, GullinBustin approved these changes

2024-04-15 09:12 UTC, merged