Ingk 876 add ruff
ingeniamc/ingenialink-python pull request #408
Opened 2024-05-07 09:31 UTC by MartinALL91

### Description

Add ruff for code formatting and linter.

Fixes # INGK-876

### Type of change

- Remove black from the project.
- Add ruff as a code formatter and linter.
- Fix ruff errors.

### Tests
- Add Jenkins stage for checking errors.

### Code formatting

- [x] Use the ruff package to format the code: `ruff format ingenialink tests`.

### Others
- [x] Set fix version field in the Jira issue.

2024-05-09 12:33 UTC, GullinBustin requested changes

2024-05-09 12:33 UTC, GullinBustin commented on ingenialink/ethercat/network.py
> +    pass
Maybe you can remove these lines

2024-05-09 12:42 UTC, MartinALL91 commented on ingenialink/ethercat/network.py
> +    pass
Done

2024-05-09 14:27 UTC, GullinBustin approved these changes

2024-05-10 13:23 UTC, pzinemanas approved these changes

2024-05-10 13:24 UTC, merged